server:
  port: 8989

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lorian_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: guoqiuwen1904
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 2MB
  redis:
    host: 192.168.101.69
    port: 6379

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: CAlyIG0N0ZZk0DlUoje2Nt2Ri4GHk11sw6ra1AqD
  secretKey: 9I5bI87SViMVVd-XYVMiOoddwHVoqwwqARUeFOMr
  bucket: lorian-blog